Repository BHoM/BHoM_UI, pull requests merged in 2020-01, with the labels that each got.

#181 Clear global menu when GH is unloaded
  BHoM_UI/Global/GlobalSearch.cs
  BHoM_UI/Global/SearchMenu.cs
  BHoM_UI/Global/SearchMenu_WinForm.cs
  BHoM_UI/Global/SearchMenu_Wpf.cs
Labels: type:bug

#184 Fix slow GetProperty component
  BHoM_UI/Components/Engine/GetProperty.cs
Labels: type:bug

#180 Improved error message when exception reached Caller.Run
  BHoM_UI/Templates/Caller.cs
Labels: type:question

#195 Update CI files
  .ci/run-compliance-tests.yml
Labels: type:compliance
